arrowParens: 'avoid'
bracketSpacing: true
endOfLine: 'lf'
jsxSingleQuote: true
printWidth: 120
proseWrap: 'preserve'
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'
useTabs: false
overrides:
  - files: 'README.md'
    options:
      printWidth: 50
  - files: '*.spec.ts'
    options:
      printWidth: 70
