release:
  branches:
    - master
plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: docs
          scope: README
          release: patch
  - - '@semantic-release/exec'
    - prepareCmd: npx npm run lint
  - - '@semantic-release/exec'
    - prepareCmd: npx npm test
  - - '@semantic-release/exec'
    - prepareCmd: npx npm run s:a && npx npm run b:a
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - npmPublish: false
  - - '@semantic-release/npm'
    - pkgRoot: projects/ngrx-correlation-id
      npmPublish: false
  - - '@semantic-release/npm'
    - tarballDir: tmp
      npmPublish: false
      pkgRoot: dist/ngrx-correlation-id
  - - '@semantic-release/github'
    - assets:
        - tmp/*.tgz
      successComment: >-
        [v${nextRelease.version}](https://github.com/satanTime/ngrx-correlation-id/releases/tag/v${nextRelease.version})
        has been released and contains a fix for the issue.
        Feel free to reopen the issue or to submit a new one if you meet any problems.
      failTitle: false
      failComment: false
      labels: false
      releasedLabels:
        - released
        - >-
          v${nextRelease.version}
  - - '@semantic-release/git'
    - message: 'chore(release): v${nextRelease.version}'
      assets:
        - projects/ngrx-correlation-id/package.json
        - CHANGELOG.md
        - package.json
        - package-lock.json
