version: '3'

services:
  core:
    image: satantime/puppeteer-node:16.17.1
    working_dir: /app
    volumes:
      - .:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --omit=optional

  a6:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a6:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a7:
    image: satantime/puppeteer-node:8.17.0
    working_dir: /app
    volumes:
      - ./e2e/a7:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a8:
    image: satantime/puppeteer-node:10.24.1
    working_dir: /app
    volumes:
      - ./e2e/a8:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a9:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a9:/app
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a10:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a10:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a11:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a11:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a12:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a12:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

  a13:
    image: satantime/puppeteer-node:12.22.12
    working_dir: /app
    volumes:
      - ./e2e/a13:/app
      - gyp:/root/.node-gyp
      - npm:/root/.npm
    command:
      - npm
      - install
      - --no-audit
      - --no-optional

volumes:
  npm:
  gyp:
